---
- name: Get the influx and telegraf repo key via apt_key
  apt_key:
   url: https://repos.influxdata.com/influxdata-archive.key
   state: present

- name: Install influx and telegraf repo
  apt_repository:
    repo: deb https://repos.influxdata.com/debian focal stable
    state: present

- name: Install "influxdb"
  apt:
    name: influxdb
    state: latest
    update_cache: no

- name: Set "influxdb" state "started" and enabled "yes"
  service:
    name: influxdb
    state: started
    enabled: yes  

#TELEGRAF below this line
- name: Install "telegraf"
  apt:
    name: telegraf
    state: latest
    update_cache: no

#InfluxDB request logging supression
- name: Template "influxdb.conf" file "influxdb.conf.j2" to remote host "/etc/influxdb/influxdb.conf"
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
#    owner: OPTIONAL_UESR
#    mode: OPTIONAL
#  no_log: ONLY_FOR_THINGS_WITH_SECRETS_IN_TEMPLATE
  notify: Restart influxdb

#Telegraf config
- name: Template "telegraf.conf" file "telegraf.conf.j2" to remote host "/etc/telegraf/telegraf.conf"
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
#    owner: OPTIONAL_UESR
#    mode: OPTIONAL
#  no_log: ONLY_FOR_THINGS_WITH_SECRETS_IN_TEMPLATE
  notify: Restart telegraf

- name: Set "telegraf" state "started" and enabled "yes"
  service:
    name: telegraf
    state: started
    enabled: yes


#Below this line is the InfluxDB stats exporter.
- name: Download "influx_stats_exporter_linux_amd64"
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/

- name: Setting mode "0755" "/usr/local/bin/influx_stats_exporter_linux_amd64"
  file:
    path: /usr/local/bin/influx_stats_exporter_linux_amd64
    mode: 0755

- name: Template "prometheus-influxdb-stats-exporter.service" file "prometheus-influxdb-stats-exporter.service.j2" to remote host "TOLONG"
  template:
    src: prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    owner: prometheus
    group: prometheus
#  no_log: ONLY_FOR_THINGS_WITH_SECRETS_IN_TEMPLATE
  notify:
    - Reload daemons
    - Restart prometheus-influxdb-stats-exporter

- name: Set "prometheus-influxdb-stats-exporter" state "started" and enabled "yes"
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes  


#This is for backups
#First to make the dir that the influx backups go to in the BACKUP_USER /home
- name: Make "/home/backup/influxdb" at "/home/backup/influxdb" 
  file:
    path: /home/backup/influxdb
    state: directory
    mode: "0700"
    owner: "{{ backup_user }}"
    group: influxdb

#Tempalte cron tab for influx
- name: Template "influxdb-backup" file "influxdb-backup.j2" to remote host "/etc/cron.d/influxdb-backup"
  template:
    src:  influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
    owner: root
    group: root
    mode: "0644"
#  no_log: ONLY_FOR_THINGS_WITH_SECRETS_IN_TEMPLATE
 # notify: HANDLER
