---
- name: Install "rsyslog"
  apt:
    name: rsyslog
    state: latest
    update_cache: no

- name: Template "50-telegraf.conf" file "50-telegraf.conf.j2" to remote host "/etc/rsyslog.d/50-telegraf.conf"
  template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
#    owner: OPTIONAL_UESR
#    mode: OPTIONAL
#  no_log: ONLY_FOR_THINGS_WITH_SECRETS_IN_TEMPLATE
  notify: Restart rsyslog

#make sure service is started and enabled
- name: Set "rsyslog" state "started" and enabled "yes"
  service:
    name: rsyslog
    state: started
    enabled: yes  