---
- name: Check if nessary directories for grafana exist if not create
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  loop:
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Teplate "grafana.ini" to /opt/grafana/grafana.ini
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart grafana docker

- name: Copy datasource.yaml to grafana
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasource.yaml
  notify: Restart grafana docker

- name: Copy dashboard.yaml to grafana
  template:
    src: dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana docker

- name: Copy grafana dashboards
  copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - syslog
    - mysql
  notify: Restart grafana docker

- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always # need this so it runs again on reboot