- name: Create necessary directories for grafana
  file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  loop:
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Template "grafana.ini" to "/opt/grafana/grafana.ini"
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart grafana docker
  no_log: yes

- name: Template "datasource.yaml" to "/opt/grafana/provisioning/datasources/datasource.yaml"
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasource.yaml
  notify: Restart grafana docker

- name: Template "dashboard.yaml" to "/opt/grafana/provisioning/dashboards/dashboard.yaml"
  template:
    src: dashboard.yaml
    dest: /opt/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana docker
  no_log: yes


- name: Copy grafana dashboards to machine
  copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - syslog
    - mysql
    - influx-syslog
  notify: Restart grafana docker

- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always


