---
- name: Install uwsgi packages
  apt:
    name:
    - uwsgi
    - uwsgi-plugin-python3
    state: latest


- name: Copy over uwsgi config file
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify: Restart uwsgi

- name: Set uwsgi state "started" and enabled "yes"
  service:
    name: uwsgi
    state: started
    enabled: yes  