---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags:
    - initial_setup

- name: DNS Server
  hosts: dns_servers
  roles:
    - bind
  tags:
    - dns_server

- name: Database Server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - database_server
    - m

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  roles:
      - prometheus
      - nginx
  tags:
    - prometheus

- name: InfluxDB and Telegraf
  hosts: influxdb_servers
  roles:
    - influxdb
  tags:
    - influxdb

- name: Pinger
  hosts: pinger
  become: yes
  roles:
    - pinger
  tags:
    - pinger

- name: Nginx
  hosts: web_servers
  roles:
    - docker
    - agama
    - nginx
  tags:
    - nginx
    - x

- name: Internal web servers
  hosts: internal_web_servers
  become: yes
  roles:
      - docker
      - nginx
  tags:
      - internal_web

- name: grafana
  hosts: all
  roles:
      - init
      - grafana
  tags:
    - grafana





  

