---
- name: Initial setup
  hosts: all
  roles:
    - init
  tags:
    - init
    
- name: DNS Server
  hosts: dns_servers
  roles:
    - bind
  tags:
    - dns_server

- name: Database Server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - database_server
    - m

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  roles:
      - prometheus
      - nginx
  tags:
    - prometheus

- name: InfluxDB and Telegraf
  hosts: influxdb_servers
  roles:
    - influxdb
  tags:
    - influxdb

- name: Pinger
  hosts: pinger
  become: yes
  roles:
    - pinger
  tags:
    - pinger

- name: Web servers
  hosts: web_servers
  roles:
    - docker
    - agama
    #- nginx
    #- uwsgi
  tags:
    - application
    - x

- name: Internal web servers
  hosts: internal_web_servers
  become: yes
  roles:
      - docker
      - nginx
  tags:
      - internal_web

- name: grafana
  hosts: grafana_servers
  roles:
      - init
      - grafana
  tags:
    - grafana

- name: Keepalived
  hosts: keepalived
  become: yes
  roles:
      - keepalived
  tags:
      - keep

- name: Haproxy
  hosts: haproxy
  become: yes
  roles:
      - haproxy
  tags:
      - ha



  

