{
 "title": "MainDash",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Influx db status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "R-Syslog",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "query": "SELECT * FROM \"syslog\" LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Consumption by VM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes - node_memory_MemFree_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pinger stats per ping (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "cloudflare.com",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"rtt\") FROM \"latency\" WHERE (\"dst\"::tag = 'cloudflare.com') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "cloudflare.com" }
     ]
    },
    {
     "alias": "erickhunter-1",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"rtt\") FROM \"latency\" WHERE (\"dst\"::tag = 'cloudflare.com') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "erickhunter-1" }
     ]
    },
    {
     "alias": "erickhunter-2",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"rtt\") FROM \"latency\" WHERE (\"dst\"::tag = 'cloudflare.com') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "erickhunter-2" }
     ]
    },
    {
     "alias": "news.err.ee",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"rtt\") FROM \"latency\" WHERE (\"dst\"::tag = 'cloudflare.com') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "news.err.ee" }
     ]
    },
    {
     "alias": "telia.ee",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "query": "SELECT mean(\"rtt\") FROM \"latency\" WHERE (\"dst\"::tag = 'cloudflare.com') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "telia.ee" }
     ]
    }
   ]
  },
  {
   "title": "Average CPU load by Machine",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg  by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}