{
 "title": "main",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "haproxy status per backend",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"ErickHunter-2:9101\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Keepalived Slave/Master",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx status + amount of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "targets": [
    { "expr": "rate(nginx_up[1m])" },
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bind_UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU load per VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "Haproxy up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mysql status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory per node/vm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL status + amount of selects per minute ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "rate(mysql_up[1m])" },
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  {
   "title": "A DNS queries per min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 24 },
   "targets": [
    { "expr": "rate(bind_up[1m])" },
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  {
   "title": "InfluxDB health ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(influxdb_exporter_stats_query_success[1m])"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * from latency group by \"dst\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  }
 ]
}