---
- name: Creating folder /opt/agama
  file:
    path: /opt/agama
    state: directory

- name: Download agama container file
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Download agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py

- name: Create agama docker image file
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start Agama Docker containers
  community.docker.docker_container:
    name: "agama-{{ item + 1 }}"
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    published_ports: "{{ agama_port + item }}:8000"
    volumes:
      - "/etc/resolv.conf:/etc/resolv.conf"
    restart_policy: always
  loop: "{{ range(agama_containers_count) }}"

- name: Set CNAME records
  delegate_to: ErickHunter-3
  nsupdate:
    key_algorithm: "hmac-sha256"
    key_name: "nsupdate"
    key_secret: "{{ dns_update_key }}"
    server: "localhost"
    zone: "{{ my_domain }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items | selectattr('key', 'in', ['www-1', 'www-2']) }}"