---
- name: Create user pinger
  user:
    name: pinger

- name: Install "fping"
  apt:
    name: fping
    state: latest
    update_cache: no

- name: Make "DIRECTORY" at "/etc/pinger" 
  file:
    path: /etc/pinger
    state: directory

- name: Template "pinger.sh" file "pinger.sh.j2" to remote host "/usr/local/bin/pinger"
  template:
    src: pinger.sh.j2
    dest: /usr/local/bin/pinger
    owner: pinger
    group: pinger
    mode: '0744'
  notify:
    - Reload daemons
    - Restart pinger

- name: Template "pinger.conf" file "pinger.conf.j2" to remote host "/etc/pinger/pinger.conf"
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify:
    - Reload daemons
    - Restart pinger

- name: Template "pinger.conf" file "pinger.service" to remote host "/etc/systemd/system/pinger.service"
  template:
    src: pinger.service.j2
    dest: /etc/systemd/system/pinger.service
  notify:
    - Reload daemons
    - Restart pinger

- name: Set "pinger" state "started" and enabled "yes"
  service:
    name: pinger
    state: started
    enabled: yes  