---
- name: Restart telegraf
  service:
    name: telegraf
    state: restarted

- name: Restart influxdb
  service:
    name: influxdb
    state: restarted

- name: Reload daemons
  shell: systemctl daemon-reload

- name: Restart prometheus-influxdb-stats-exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
