---
#- name: Ansible ping module
#  ansible.builtin.ping:

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

#- name: Create user(s)
#  user:
#    name: "{{ item.name }}"
#  loop: "{{ users }}"

#- name: Set authorized keys
#  ansible.posix.authorized_key:
#    user: "{{ item.name }}"
#    state: present
#    key: "{{ item.key }}"
#    validate_certs: False
#  loop: "{{ users }}"


#This is for the node exporter for vm metrics, as per lab this is in the init role.
- name: Install "prometheus-node-exporter"
  apt:
    name: prometheus-node-exporter
    state: latest
    update_cache: no


- name: Set "prometheus-node-exporter" state "started" and enabled "yes"
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

#this was part of lab7 so that you don't get issues with installing grafana.
- name: Ensure ca-certificates is installed at a specific version
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present